CREATE TABLE PROJECT (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	AGE INT,
	GENDER VARCHAR(50),
	ITEM_PURCHASED VARCHAR(50),
	CATEGORY VARCHAR(50),
	PURCHASE_AMOUNT_USD NUMERIC(10,2),
	LOCATION VARCHAR(50),
	SIZE VARCHAR(50),
	COLOR VARCHAR(50),
	SEASON VARCHAR(50),
	REVIEW_RATING REAL,
	SUBSCRIPTION_STATUS VARCHAR(50),
	SHIPPING_TYPE VARCHAR(50),
	DISCOUNT_APPLIED VARCHAR(50),
	PROMO_CODE_USED VARCHAR(50),
	PREVIOUS_PURCHASES INT,
	PAYMENT_METHOD VARCHAR(50),
	FREQUENCY_OF_PURCHASES VARCHAR(50)
);

SELECT * FROM PROJECT;

------------ ITEM PURCHASED LIST---------

select distinct item_purchased
from project;

-------------- TOTAL SALES ACC TO ITEM-------

SELECT
	ITEM_PURCHASED,
	SUM(PURCHASE_AMOUNT_USD) AS "total_sales"
FROM
	PROJECT
GROUP BY
	ITEM_PURCHASED
ORDER BY
	"total_sales" DESC;

------------- TOTAL SALES ACC TO CATEGORY---
SELECT
	CATEGORY,
	SUM(PURCHASE_AMOUNT_USD) AS "total_sales"
FROM
	PROJECT
GROUP BY
	CATEGORY
ORDER BY
	"total_sales" DESC;

--- MALE AND FEMALE VOLUME---

SELECT Gender,
count(*) as "total"
from project
group by Gender;


----- TOTAL SALES ---------

select 
sum(purchase_amount_USD) as "total_sales"
from project;

----- SALES BY LOCATION--------

select distinct location
from project;

SELECT
	LOCATION,
	SUM(PURCHASE_AMOUNT_USD) AS "total"
FROM
	PROJECT
GROUP BY
	LOCATION
ORDER BY
	"total" DESC;

--- sales by size---

SELECT
	SIZE,
	SUM(PURCHASE_AMOUNT_USD) AS "total"
FROM
	PROJECT
GROUP BY
	SIZE
ORDER BY
	"total" DESC;

---- MOST SALE PRODUCT AND COLOR ------

SELECT 
Item_Purchased ,COLOR,
	SUM(PURCHASE_AMOUNT_USD) AS "total"
FROM
	PROJECT
GROUP BY
	COLOR, Item_Purchased
ORDER BY
	"total" DESC;

---- MAX AND MIN AMT PAID BY CUSTOMERS----

SELECT
	MAX(PURCHASE_AMOUNT_USD) AS "Highest",
	MIN(PURCHASE_AMOUNT_USD) AS "Lowest"
FROM
	PROJECT;

------- SALES ACCORDING TO SEASON-----

SELECT
	SEASON,
	SUM(PURCHASE_AMOUNT_USD) AS "total"
FROM
	PROJECT
GROUP BY
	SEASON
ORDER BY
	"total" DESC;
----------- CUSTOMERS REVIEW RATE---- 

SELECT
	CASE
		WHEN REVIEW_RATING >= 3.5 THEN 'Customer_Satisfied'
		ELSE 'Not_Satisfied'
	END AS SATISFACTION_STATUS,
	COUNT(*) AS TOTAL_CUSTOMERS
FROM
	PROJECT
GROUP BY
	SATISFACTION_STATUS
ORDER BY
	TOTAL_CUSTOMERS DESC;

----------- SUBSCRIPTION STATUS----------

SELECT
	SUBSCRIPTION_STATUS,
	COUNT(*) AS TOTAL
FROM
	PROJECT
GROUP BY
	SUBSCRIPTION_STATUS;
--------- MOST PREFERABLE SHIPPING TYPE BY CUSTOMER-----

SELECT
	SHIPPING_TYPE,
	SUM(PURCHASE_AMOUNT_USD) AS "total"
FROM
	PROJECT
GROUP BY
	SHIPPING_TYPE
ORDER BY
	"total" DESC;

-------- DISCOUNT APPLIED BY CUSTOMERS------------

SELECT
	DISCOUNT_APPLIED,
	COUNT(*) AS TOTAL
FROM
	PROJECT
GROUP BY
	DISCOUNT_APPLIED;

---------- MOST USED PAYMENT METHOD BY CUSTOMERS

SELECT
	PAYMENT_METHOD,
	COUNT(*) AS "TOTAL"
FROM
	PROJECT
GROUP BY
	PAYMENT_METHOD;
------------ FREQUENCY OF PURCHASES BY CUSTOMERS--------- 

SELECT
	FREQUENCY_OF_PURCHASES,
	COUNT(*) AS "total"
FROM
	PROJECT
GROUP BY
	FREQUENCY_OF_PURCHASES
ORDER BY
	"total" DESC;

---------- REVENUE CONTRIBUTION BY EACH CATEGORY------

SELECT 
    CATEGORY,
    SUM(PURCHASE_AMOUNT_USD) AS total_sales,
    ROUND(SUM(PURCHASE_AMOUNT_USD) * 100.0 / (SELECT SUM(PURCHASE_AMOUNT_USD) FROM PROJECT), 2) AS revenue_percentage
FROM PROJECT
GROUP BY CATEGORY
ORDER BY total_sales DESC;

---- BY AGE---

SELECT 
CASE 
WHEN AGE BETWEEN 30 AND 40 THEN '30-40'
WHEN AGE BETWEEN 40 AND 50 THEN '40-50'
WHEN AGE BETWEEN 50 AND 60 THEN '50-60'
ELSE '60+'
END AS AGE_WISE_SEGMENTATION,
COUNT (*) AS TOTAL_CUSTOMERS

FROM PROJECT
GROUP BY AGE_WISE_SEGMENTATION
ORDER BY TOTAL_CUSTOMERS DESC;


